# Generated by Django 5.1.4 on 2025-01-21 20:43

import book.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_chapter_serial_number_alter_chapter_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commentary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=models.SET(book.models.get_sentinel_user),
                        related_name="commentaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaries",
                        to="book.book",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="book.commentary",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "commentaries",
                "ordering": ["-date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("book__isnull", False),
                            ("parent__isnull", False),
                            _connector="OR",
                        ),
                        name="has_parent_or_book_to_refer_to",
                    )
                ],
            },
        ),
    ]
