# Generated by Django 5.1.4 on 2025-03-17 15:10

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_bookmonthview"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=256,
                null=True,
                storage=book.models.BookRelatedS3Storage,
                upload_to=book.models.get_chapter_s3_path,
            ),
        ),
    ]
