# Generated by Django 5.1.4 on 2025-03-18 03:47

import book.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_book_image_alter_chapter_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="picture",
            field=models.FileField(
                default=django.utils.timezone.now,
                max_length=256,
                storage=book.models.AuthorS3Storage,
                upload_to=book.models.get_picture_s3_path,
            ),
            preserve_default=False,
        ),
    ]
