# Generated by Django 5.1.4 on 2025-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_chapter_serial_number_alter_chapter_book"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="library",
            field=models.ManyToManyField(related_name="users", to="book.book"),
        ),
    ]
